#!/usr/bin/env python3
"""Regenerate correctness/fixtures/golden.tsv — the §1 independent FP32 golden.

Run OFFLINE (by a maintainer), NOT in CI. Loads the FP32 PyTorch model
jina-embeddings-v5-text-nano-retrieval via sentence-transformers and encodes each row of
inputs.tsv with `prompt_name=role` (query/document) — the sentence-transformers way; the
model applies its own "Query: "/"Document: " prompt, so we do NOT prefix text by hand
(the llama.cpp side does that instead). Last-token pooling, L2-normalized, dim 768. This
is independent of the GGUF/llama.cpp path, so the parity
check scripts/correctness.sh runs (IQ4_NL GGUF vs this golden, cosine >= 0.98) is not
circular — it mirrors the downstream GGUF-vs-PyTorch-FP32 benchmark that caught v0.1.151-1.

Deps (heavy; offline): torch>=2.8, transformers>=5.1, sentence-transformers, peft>=0.15.
scripts/gen-golden.sh sets up a venv and runs this. Output labels are "<id>|last",
matching the `correctness` crate's emit, so `compare` diffs the LAST embeddings.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
FIX = os.path.join(ROOT, "correctness", "fixtures")
INPUTS = os.path.join(FIX, "inputs.tsv")
GOLDEN = os.path.join(FIX, "golden.tsv")

MODEL_ID = os.environ.get("CORRECTNESS_GOLDEN_MODEL_ID", "jinaai/jina-embeddings-v5-text-nano-retrieval")
MODEL_REV = os.environ.get("CORRECTNESS_GOLDEN_MODEL_REV", "main")
EXPECT_DIM = 768
# Exact jina prefixes (model config_sentence_transformers.json "prompts"); MUST match the
# `correctness` crate's QUERY_PREFIX/DOCUMENT_PREFIX so both sides embed identical strings.
PREFIX = {"query": "Query: ", "document": "Document: "}


def load_inputs():
    rows = []
    with open(INPUTS, encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\r\n")
            if not line.strip() or line.lstrip().startswith("#"):
                continue
            parts = line.split("\t", 3)
            if len(parts) < 4 or not parts[0] or not parts[3]:
                sys.exit(f"malformed inputs line (need id<TAB>role<TAB>group<TAB>text): {line!r}")
            rid, role, _group, text = parts
            if role not in PREFIX:
                sys.exit(f"input {rid!r}: role must be query|document, got {role!r}")
            rows.append((rid, role, text))
    if not rows:
        sys.exit("inputs fixture has no rows")
    return rows


def main():
    import torch
    from sentence_transformers import SentenceTransformer

    rows = load_inputs()
    print(f"[golden] {len(rows)} inputs; loading {MODEL_ID}@{MODEL_REV} (FP32, cpu)")
    model = SentenceTransformer(
        MODEL_ID,
        revision=MODEL_REV,
        trust_remote_code=True,
        device="cpu",
        model_kwargs={"torch_dtype": torch.float32},
    )

    # Resolve the concrete commit sha for provenance (best-effort).
    resolved_rev = MODEL_REV
    try:
        from huggingface_hub import HfApi
        resolved_rev = HfApi().model_info(MODEL_ID, revision=MODEL_REV).sha or MODEL_REV
    except Exception as e:  # noqa: BLE001
        print(f"[golden] could not resolve revision sha ({e}); recording {MODEL_REV}")

    lines = []
    for rid, role, text in rows:
        # sentence-transformers: pass RAW text + prompt_name (do NOT manually prefix).
        # prompt_name=role makes the model apply its own "Query: "/"Document: " prompt,
        # matching what the llama.cpp side prepends literally. Manual-prefixing here would
        # double it.
        emb = model.encode(
            text, prompt_name=role, normalize_embeddings=True, convert_to_numpy=True
        )
        if emb.shape[-1] != EXPECT_DIM:
            sys.exit(f"input {rid}: got dim {emb.shape[-1]}, expected {EXPECT_DIM}")
        csv = ",".join(f"{v:.9g}" for v in emb.tolist())
        lines.append(f"{rid}|last\t{csv}")

    header = [
        "# GOLDEN reference embeddings (§1). label<TAB>f0,f1,...  Generated by scripts/gen-golden.py.",
        "# DO NOT EDIT BY HAND. Regenerate when inputs.tsv / the reference GGUF / the golden model rev changes.",
        f"#   golden model : {MODEL_ID}  rev {resolved_rev}",
        f"#   dtype/dim    : float32 / {EXPECT_DIM},  pooling: last,  normalize: L2",
        f'#   prefixes     : query="{PREFIX["query"]}"  document="{PREFIX["document"]}"',
        "#   compared to  : v5-nano-retrieval-IQ4_NL.gguf  (threshold cosine >= 0.98, quant vs FP32)",
    ]
    with open(GOLDEN, "w", encoding="utf-8") as f:
        f.write("\n".join(header) + "\n")
        f.write("\n".join(lines) + "\n")
    print(f"[golden] wrote {GOLDEN} ({len(rows)} inputs, LAST pooling). Review + commit it.")


if __name__ == "__main__":
    main()
