#!/usr/bin/env bash
#
# Regenerate correctness/fixtures/golden.tsv — the §1 independent golden reference.
#
# Run this OFFLINE (by a maintainer), NOT in CI. It builds the UPSTREAM official
# `llama-embedding` binary from the pinned llama.cpp commit with GENERIC flags
# (-march=armv8-a) — an implementation independent of the tuned archives this repo ships,
# so the golden parity check in scripts/correctness.sh is not circular. Commit the
# resulting golden.tsv. Rerun whenever the reference model (reference-model.env) or the
# pinned llama.cpp commit (config.env EXPECTED_LLAMA_CPP_COMMIT) changes.
#
# Requires: cmake, a C/C++ toolchain, jq, curl. Output format matches the `correctness`
# crate's emit: label "<id>|<pooling>" then a TAB then comma-separated floats.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "${ROOT}/scripts/config.env"

FIX="${ROOT}/correctness/fixtures"
INPUTS="${FIX}/inputs.tsv"
GOLDEN="${FIX}/golden.tsv"
WORK="${ROOT}/.build/golden"
SRC="${WORK}/llama-cpp-rs"
LLAMA_CPP="${SRC}/llama-cpp-sys-2/llama.cpp"
BUILD="${WORK}/build"
MODEL="${WORK}/reference-model.gguf"
GENERIC_MARCH="armv8-a"

mkdir -p "${WORK}"
log() { printf '\033[1;35m[golden]\033[0m %s\n' "$*"; }

# --- reference model ---------------------------------------------------------------
source "${FIX}/reference-model.env"
: "${CORRECTNESS_MODEL_URL:?set CORRECTNESS_MODEL_URL in reference-model.env}"
: "${CORRECTNESS_MODEL_SHA256:?set CORRECTNESS_MODEL_SHA256 in reference-model.env}"
verify() { echo "${CORRECTNESS_MODEL_SHA256}  ${MODEL}" | sha256sum -c - >/dev/null 2>&1; }
if [[ ! -f "${MODEL}" ]] || ! verify; then
  log "fetching reference model"
  curl -fSL "${CORRECTNESS_MODEL_URL}" -o "${MODEL}"
  verify || { echo "[golden] reference model sha256 mismatch" >&2; exit 1; }
fi

# --- upstream llama.cpp @ pinned commit --------------------------------------------
if [[ ! -d "${SRC}/.git" ]]; then
  log "clone ${CRATE_REPO} @ ${CRATE_TAG} (brings pinned llama.cpp submodule)"
  git clone --depth 1 --branch "${CRATE_TAG}" --recursive "${CRATE_REPO}" "${SRC}"
fi
GOT="$(git -C "${LLAMA_CPP}" rev-parse HEAD)"
[[ "${GOT}" == "${EXPECTED_LLAMA_CPP_COMMIT}" ]] \
  || { echo "[golden] llama.cpp commit ${GOT} != expected ${EXPECTED_LLAMA_CPP_COMMIT}" >&2; exit 1; }
DESCRIBE="$(git -C "${LLAMA_CPP}" describe --tags 2>/dev/null || echo unknown)"

# --- build ONLY the llama-embedding example, GENERIC flags -------------------------
log "cmake build llama-embedding (-march=${GENERIC_MARCH}, GGML_NATIVE=OFF)"
cmake -S "${LLAMA_CPP}" -B "${BUILD}" \
  -DCMAKE_BUILD_TYPE=Release \
  -DGGML_NATIVE=OFF -DGGML_CPU_ARM_ARCH="${GENERIC_MARCH}" \
  -DCMAKE_C_FLAGS="-O3 -march=${GENERIC_MARCH}" \
  -DCMAKE_CXX_FLAGS="-O3 -march=${GENERIC_MARCH}" \
  -DLLAMA_BUILD_EXAMPLES=ON -DLLAMA_BUILD_TESTS=OFF -DLLAMA_BUILD_SERVER=OFF -DLLAMA_CURL=OFF >/dev/null
cmake --build "${BUILD}" --target llama-embedding -j "$(nproc)" >/dev/null
EMB="$(find "${BUILD}" -name llama-embedding -type f -perm -u+x -print -quit)"
[[ -n "${EMB}" ]] || { echo "[golden] llama-embedding binary not found under ${BUILD}" >&2; exit 1; }

# --- inputs -> prompts (order preserved; id list parallel to prompt lines) ---------
mapfile -t IDS < <(awk -F'\t' '!/^[[:space:]]*#/ && NF>=3 && $1!="" {print $1}' "${INPUTS}")
PROMPTS="${WORK}/prompts.txt"
awk -F'\t' '!/^[[:space:]]*#/ && NF>=3 && $1!="" {print $3}' "${INPUTS}" > "${PROMPTS}"
[[ "${#IDS[@]}" -gt 0 ]] || { echo "[golden] no inputs parsed from ${INPUTS}" >&2; exit 1; }
log "${#IDS[@]} inputs"

# --- generate golden.tsv -----------------------------------------------------------
{
  echo "# GOLDEN reference embeddings (§1). label<TAB>f0,f1,...  Generated by scripts/gen-golden.sh."
  echo "# DO NOT EDIT BY HAND. Regenerate when the reference model or llama.cpp commit changes."
  echo "#   llama.cpp commit : ${EXPECTED_LLAMA_CPP_COMMIT}  (describe: ${DESCRIBE})"
  echo "#   reference model  : $(basename "${CORRECTNESS_MODEL_URL}")  sha256 ${CORRECTNESS_MODEL_SHA256}"
  echo "#   build flags      : -O3 -march=${GENERIC_MARCH}  (generic; no dotprod/fp16/mtune)"
  echo "#   tool             : ${EMB##*/} --pooling {mean,last} --embd-normalize 2 --embd-output-format json"
} > "${GOLDEN}"

for pool in mean last; do
  log "llama-embedding --pooling ${pool}"
  OUT="${WORK}/emb.${pool}.json"
  "${EMB}" -m "${MODEL}" --pooling "${pool}" -f "${PROMPTS}" \
    --embd-normalize 2 --embd-output-format json > "${OUT}"
  n="${#IDS[@]}"
  for ((i = 0; i < n; i++)); do
    emb="$(jq -r ".data[${i}].embedding | map(tostring) | join(\",\")" "${OUT}")"
    [[ -n "${emb}" && "${emb}" != "null" ]] || { echo "[golden] no embedding for index ${i} (${pool})" >&2; exit 1; }
    printf '%s|%s\t%s\n' "${IDS[$i]}" "${pool}" "${emb}" >> "${GOLDEN}"
  done
done

log "wrote ${GOLDEN} (${#IDS[@]} inputs x 2 poolings). Review + commit it."
